[versions]
kotlin = "2.1.0"
ktor="3.2.3"
logback="1.5.13"
kmongo="4.11.0"
tg-bot="0.13.2"

[libraries]
ktor-client-core-jvm = { module = "io.ktor:ktor-client-core-jvm" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp-jvm" }
ktor-client-auth = { module = "io.ktor:ktor-client-auth" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json" }
ktor-client-serialization = { module = "io.ktor:ktor-client-serialization" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
mongodb-driver-kotlin-coroutine = { module = "org.mongodb:mongodb-driver-kotlin-coroutine", version.ref = "kmongo" }
telegram-bot-core = { module = "io.github.dehuckakpyt.telegrambot:telegram-bot-core", version.ref = "tg-bot" }
mongodb-bson-kotlinx = { module = "org.mongodb:bson-kotlinx", version.ref = "kmongo" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ktor = { id = "io.ktor.plugin",  version.ref = "ktor" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }